automation/urls.py
from django.conf.urls import patterns, url

from automation import views

urlpatterns = patterns('',
    url(r'crajax/', views.CRView.as_view(), name="crajax"),
    url(r'testsajax/', views.TestsView.as_view(), name="testsajax"),
    url(r'^(?P<project>.+)', views.index, name='index'),
)

pgacms/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from pgacms.views import AdminRedirectView, TestFormView
from automation.views import SelectView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pgacms.views.home', name='home'),
    # url(r'^pgacms/', include('pgacms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', AdminRedirectView.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^automation/', include('automation.urls', namespace="automation")),
    url(r'^upload/', include('upload.urls', namespace="upload")),
    url(r'^select/(?P<project>.+)', SelectView.as_view(), name='select'),



    url(r'^testform/', TestFormView.as_view())
)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

pgacms/views.py
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.shortcuts import render

class AdminRedirectView(View):
    def get(self, form):
        return HttpResponseRedirect('/admin/')


class TestFormView(View):
	def get(self, request):
		return render(request, 'testform.html')
	def post(self, request):
		print request.FILES
		return render(request, 'testform.html')

pgacms/templates/chart_module.html
{% extends "admin_tools/dashboard/module.html" %}
{% load i18n %}
{% block module_content %}
<script>
var savedhtml = '';
var savedproj = '';

function handleTestsClick() {
    var count = 0;
    var checkedValue = $('.project:checkbox:checked').map(function() {
        count++;
        return this.name;
    }).get().join(",");
    if (count <= 1) {
      alert('At least two tests must be selected to compare.')
      return;
    }
    $.ajax({ type:"GET",
      url: "/automation/testsajax/",
      data: {
        'data': checkedValue
      },
      success: function(data) {
        savedhtml = document.getElementById("module").innerHTML;
        document.getElementById("heading").innerHTML= "";
        document.getElementById("crbutton").setAttribute("style", "display: none;");
        document.getElementById("testsbutton").setAttribute("value", "Back");
        document.getElementById("testsbutton").setAttribute("onClick", "backClick();");
        document.getElementById("module").innerHTML= "<center> <img src=//" + data.url + "> </center>";
        return;
      },
  });
}

function handleCRClick() {
    if (isNaN(document.getElementById("days").value) == true) {
        alert('Please enter a valid number for days.');
        return;
    } else if (+(document.getElementById("days").value) < 1) {
        alert('Please enter a positive number of days.');
        return;
    }
    var count = 0;
    var checkedValue = $('.project:checkbox:checked').map(function() {
        count++;
        return this.name;
    }).get().join(",");
    if (count != 1 && savedproj == '') {
      alert('Only one test can be selected to view CR history.')
      return;
    }
    var proj;
    if (savedproj != '') {
      proj = savedproj;
    } else {
      proj = checkedValue;
    }
    $.ajax({ type:"GET",
      url: "/automation/crajax/",
      data: {
        'data': proj,
        'days': document.getElementById("days").value
      },
      success: function(data) {
        if (savedproj == '') {
            savedhtml = document.getElementById("module").innerHTML;
        }
        savedproj = data.proj;
        document.getElementById("heading").innerHTML= "";
        document.getElementById("daylabel").innerHTML= "Days: ";
        document.getElementById("days").setAttribute("style", "");
        document.getElementById("crbutton").setAttribute("value", "Change Days");
        document.getElementById("testsbutton").setAttribute("value", "Back");
        document.getElementById("testsbutton").setAttribute("onClick", "backClick();");
        document.getElementById("module").innerHTML= "<center> <img src=//" + data.url + "> </center>";
        return;
      },
  });
}

function backClick(){
    document.getElementById("module").innerHTML= savedhtml;
    document.getElementById("daylabel").innerHTML= "";
    document.getElementById("days").setAttribute("style", "display: none;");
    document.getElementById("days").value = '7';
    document.getElementById("heading").innerHTML= "Select project(s):";
    document.getElementById("crbutton").setAttribute("style", "");
    document.getElementById("crbutton").setAttribute("value", "CR History");
    document.getElementById("testsbutton").setAttribute("onClick", "handleTestsClick()");
    document.getElementById("testsbutton").setAttribute("value", "Compare Tests");
    
    savedproj = '';
}
</script>

<body>
    <p>
      <span id = 'heading'>Select project(s):</span>
      <form name = "graphform" action="javascript:void(0);">
        <span id = "module">
        <ul>
          {% for item in module.children.0.project_names %}
            <li class="{% cycle 'odd' 'even' %}">
              <input type="checkbox" class="project" name="{{ item }}"> {{ item }} <br>
            </li>
          {% endfor %}
        </ul>
        </span>
        <p style="float: left;"><span id = 'daylabel'></span>
        <input type = 'text' name = 'Days' id = 'days' value = '7' style= "display: none;"></p>
        <p style="float: right;">
          &nbsp;
        <input name = "Submit" id = "crbutton" type = "submit" value="CR History" onClick="handleCRClick();">&nbsp; &nbsp;
        <input name = "Submit" id = "testsbutton" type = "submit" value="Compare Tests" onClick="handleTestsClick();">
        </p>
        <br> &nbsp;
      </form>
    </p>
</body>
{% endblock %}

pgacms/templates/project_list.html
{% extends "admin_tools/dashboard/module.html" %}
{% load i18n %}
{% block module_content %}
            <ul>
              <h2>Project Overview</h2>
            <p><a href="{{ module.children.0.testinfo.testurl }}">
              Total Tests: {{ module.children.0.testinfo.total }}
            </a><br>
            <a href="{{ module.children.0.testinfo.bugsurl }}">
              Outstanding CRs: {{ module.children.0.testinfo.bugs }}
            </a><br>
            <a href="{{ module.children.0.testinfo.weeklybugsurl }}">
              CRs in Last 7 Days
            </a><br>
            <a href="{{ module.children.0.reggroupinfo.projurl }}">
              Total Regression Runs: {{ module.children.0.reggroupinfo.count }}
            </a>
            {% if module.children.0.reggroupinfo.count != 0 %}
              <br><br>Latest Three Runs:
              {% for item in module.children.0.reggroupinfo.latest %}
                <br> &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{{ item.url }}">
                  {{ item.pass }}: &nbsp; {{ item.time }}
                </a>
              {% endfor %}
            {% endif %}
              
            </p>
            <h2>Tests By Owner</h2>
            {% for key, child in module.children.0.testlist.items %}
            {% spaceless %}
            <li class="{% cycle 'odd' 'even' %}">
            {% if child.url %}<a href="{{ child.url }}">{{ child.title }} owns {{ child.owned }} test(s)</a>{% else %}{{ child.title }}{% endif %} <br>
            </li>
            {% endspaceless %}
            {% endfor %}
            {% if module.children.0.rinfo.running == False %}
              <h2>Run Regression Tests</h2>
              <form action=" {% url 'select' module.children.0.projectinfo.name %}" method="post">
              {% csrf_token %}
              <p>
                Port Pair 1: <input type="text" name="one" value= "{{ module.children.0.projectinfo.one }}" placeholder="ip/slot/port">
                &nbsp;&nbsp;
                <input type="text" name="two"value= "{{ module.children.0.projectinfo.two }}" placeholder="ip/slot/port"><br>
                Port Pair 2: <input type="text" name="three" value= "{{ module.children.0.projectinfo.three }}" placeholder="ip/slot/port">
                &nbsp;&nbsp;
                <input type="text" name="four"value= "{{ module.children.0.projectinfo.four }}" placeholder="ip/slot/port"><br>
                Port Pair 3: <input type="text" name="five" value= "{{ module.children.0.projectinfo.five }}" placeholder="ip/slot/port">
                &nbsp;&nbsp;
                <input type="text" name="six"value= "{{ module.children.0.projectinfo.six }}" placeholder="ip/slot/port"><br>
                Port Pair 4: <input type="text" name="seven" value= "{{ module.children.0.projectinfo.seven }}" placeholder="ip/slot/port">
                &nbsp;&nbsp;
                <input type="text" name="eight"value= "{{ module.children.0.projectinfo.eight }}" placeholder="ip/slot/port"><br>
                Port Pair 5: <input type="text" name="nine" value= "{{ module.children.0.projectinfo.nine }}" placeholder="ip/slot/port">
                &nbsp;&nbsp;
                <input type="text" name="ten"value= "{{ module.children.0.projectinfo.ten }}" placeholder="ip/slot/port"> <br>
                <input type="checkbox" name="bypass"> Bypass Firmware Version Check
                <input type="submit" value="Run Regression" style="float: right;"/>
              </p>
              </form>
            {% else %}
              <h2>Regression Being Run By: {{ module.children.0.rinfo.user }}</h2>
              <form action=" {% url 'automation:index' module.children.0.projectinfo.name %}" method="get">
              {% csrf_token %}
              <p>
                Port Pair 1: <input type="text" name="one" value= "{{ module.children.0.projectinfo.one }}" placeholder="ip/slot/port" disabled>
                &nbsp;&nbsp;
                <input type="text" name="two"value= "{{ module.children.0.projectinfo.two }}" placeholder="ip/slot/port" disabled><br>
                Port Pair 2: <input type="text" name="three" value= "{{ module.children.0.projectinfo.three }}" placeholder="ip/slot/port" disabled>
                &nbsp;&nbsp;
                <input type="text" name="four"value= "{{ module.children.0.projectinfo.four }}" placeholder="ip/slot/port" disabled><br>
                Port Pair 3: <input type="text" name="five" value= "{{ module.children.0.projectinfo.five }}" placeholder="ip/slot/port" disabled>
                &nbsp;&nbsp;
                <input type="text" name="six"value= "{{ module.children.0.projectinfo.six }}" placeholder="ip/slot/port" disabled><br>
                Port Pair 4: <input type="text" name="seven" value= "{{ module.children.0.projectinfo.seven }}" placeholder="ip/slot/port" disabled>
                &nbsp;&nbsp;
                <input type="text" name="eight"value= "{{ module.children.0.projectinfo.eight }}" placeholder="ip/slot/port" disabled><br>
                Port Pair 5: <input type="text" name="nine" value= "{{ module.children.0.projectinfo.nine }}" placeholder="ip/slot/port" disabled>
                &nbsp;&nbsp;
                <input type="text" name="ten"value= "{{ module.children.0.projectinfo.ten }}" placeholder="ip/slot/port" disabled>
                {% if module.children.0.rinfo.project == True %}
                  <input type="submit" value="View Running Regression" style="float: right;"/>
                {% else %}
                  <input type="submit" value="Run Regression" style="float: right;" disabled/>
                {% endif %}
              </p>
              </form>
            {% endif %}
            </ul>

{% endblock %}

pgacms/templates/tabtest.html
{% load i18n admin_static admin_modify %}
<div class="inline-group" id="{{ inline_admin_formset.formset.prefix }}-group">
  <div class="tabular inline-related {% if forloop.last %}last-related{% endif %}">
{{ inline_admin_formset.formset.management_form }}
<fieldset class="module">
   <h2>{{ inline_admin_formset.opts.verbose_name_plural|capfirst }}</h2>
   {{ inline_admin_formset.formset.non_form_errors }}
   <table>
     <thead><tr>
     {% for field in inline_admin_formset.fields %}
       {% if not field.widget.is_hidden %}
         <th{% if forloop.first %} colspan="2"{% endif %}{% if field.required %} class="required"{% endif %}>{{ field.label|capfirst }}
         {% if field.help_text %}&nbsp;<img src="{% static "admin/img/icon-unknown.gif" %}" class="help help-tooltip" width="10" height="10" alt="({{ field.help_text|striptags }})" title="{{ field.help_text|striptags }}" />{% endif %}
         </th>
       {% endif %}
     {% endfor %}
     {% if inline_admin_formset.formset.can_delete %}<th>{% trans "Delete?" %}</th>{% endif %}
     </tr></thead>

     <tbody>
     {% for inline_admin_form in inline_admin_formset %}
        {% if inline_admin_form.form.non_field_errors %}
        <tr><td colspan="{{ inline_admin_form|cell_count }}">{{ inline_admin_form.form.non_field_errors }}</td></tr>
        {% endif %}
        <tr class="form-row {% cycle "row1" "row2" %} {% if inline_admin_form.original or inline_admin_form.show_url %}has_original{% endif %}{% if forloop.last %} empty-form{% endif %}"
             id="{{ inline_admin_formset.formset.prefix }}-{% if not forloop.last %}{{ forloop.counter0 }}{% else %}empty{% endif %}">
        <td class="original">
          {% if inline_admin_form.original or inline_admin_form.show_url %}<p>
          {% if inline_admin_form.original %} {{ inline_admin_form.original }}{% endif %}
          {% if inline_admin_form.show_url %}<a href="{% url 'admin:view_on_site' inline_admin_form.original_content_type_id inline_admin_form.original.pk %}">{% trans "View on site" %}</a>{% endif %}
            </p>{% endif %}
          {% if inline_admin_form.has_auto_field %}{{ inline_admin_form.pk_field.field }}{% endif %}
          {{ inline_admin_form.fk_field.field }}
          {% spaceless %}
          {% for fieldset in inline_admin_form %}
            {% for line in fieldset %}
              {% for field in line %}
                {% if field.is_hidden %} {{ field.field }} {% endif %}
              {% endfor %}
            {% endfor %}
          {% endfor %}
          {% endspaceless %}
        </td>
        {% for fieldset in inline_admin_form %}
          {% for line in fieldset %}
            {% for field in line %}
              <td{% if field.field.name %} class="field-{{ field.field.name }}"{% endif %}>
              {% if field.is_readonly %}
                  <p>{{ field.contents|linebreaksbr }}</p>
              {% else %}
                  {{ field.field.errors.as_ul }}
                  {{ field.field }}
              {% endif %}
              </td>
            {% endfor %}
          {% endfor %}
        {% endfor %}
        {% if inline_admin_formset.formset.can_delete %}
          <td class="delete">{% if inline_admin_form.original %}{{ inline_admin_form.deletion_field.field }}{% endif %}</td>
        {% endif %}
        </tr>
     {% endfor %}
     </tbody>
   </table>
</fieldset>
  </div>
</div>

<script type="text/javascript">

(function($) {
  $("#{{ inline_admin_formset.formset.prefix }}-group .tabular.inline-related tbody tr").tabularFormset({
    prefix: "{{ inline_admin_formset.formset.prefix }}",
    adminStaticPrefix: '{% static "admin/" %}',
    addText: "{% blocktrans with inline_admin_formset.opts.verbose_name|title as verbose_name %}Add another {{ verbose_name }}{% endblocktrans %}",
    deleteText: "{% trans 'Remove' %}"
  });
})(django.jQuery);
</script>

pgacms/templates/test.html
Hello World!

pgacms/templates/test_change_list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list %}
{% load admin_urls %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
  {% endif %}
  {% if cl.formset or action_form %}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ app_label|capfirst|escape }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              <a href="{% url cl.opts|admin_urlname:'add' %}{% if is_popup %}?_popup=1{% endif %}" class="addlink">
                {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
              </a>
            </li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% blocktrans count cl.formset.errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}

pgacms/templates/testform.html
<!doctype html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<style>
form { display: block; margin: 20px auto; background: #eee; border-radius: 10px; padding: 15px }
#progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
#bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
#percent { position:absolute; display:inline-block; top:3px; left:48%; }
</style>
</head>
<body>
<h1>Ajax File Upload Demo</h1>
 
<form id="myForm" action="testform/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
     <input type="file" size="60" name="myfile">
     <input type="submit" value="Ajax File Upload">
 </form>
 
 <div id="progress">
        <div id="bar"></div>
        <div id="percent">0%</div >
</div>
<br/>
 
<div id="message"></div>
 
<script>
$(document).ready(function()
{
 
    var options = {
    beforeSend: function()
    {
        $("#progress").show();
        //clear everything
        $("#bar").width('0%');
        $("#message").html("");
        $("#percent").html("0%");
    },
    uploadProgress: function(event, position, total, percentComplete)
    {
        $("#bar").width(percentComplete+'%');
        $("#percent").html(percentComplete+'%');
 
    },
    success: function()
    {
        $("#bar").width('100%');
        $("#percent").html('100%');
 
    },
    complete: function(response)
    {
        $("#message").html("<font color='green'>"+response.responseText+"</font>");
    },
    error: function()
    {
        $("#message").html("<font color='red'> ERROR: unable to upload files</font>");
 
    }
 
};
 
     $("#myForm").ajaxForm(options);
 
});
 
</script>
</body>
 
</html>